### ISSUE TITLE
Social Media links of Twitter, facebook, linkedin are not visible.

### ISSUE THREAD

**Issue by vinaysomawat** [mazipan/bulma-resume-template#136]
Social Media links of Twitter, Facebook, Linkedin are not visible after adding into the data.js file. Please fix it.

**Comment by mazipan** [comment]
Can you attach some screenshots, and what you expected.

**Comment by vinaysomawat** [comment]
Social Media icons and links are not visible in Linux Chrome Desktop version. 

![Screenshot from 2020-03-26 07-36-15](https://user-images.githubusercontent.com/30196269/77602906-b42c3500-6f34-11ea-8e47-985238431e03.png)

Expected:
The icons and links should visible.

**Comment by vinaysomawat** [comment]
Wait...These social media links are visible in Android Desktop mode but not in Linux chrome. Could you clarify, what is this happening? 

![WhatsApp Image 2020-03-26 at 7 36 33 AM](https://user-images.githubusercontent.com/30196269/77603071-1be28000-6f35-11ea-9846-4166cf5f8d8a.jpeg)
